import { ClerkProvider, SignIn } from "@clerk/nextjs";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <ClerkProvider>
    <html lang="en">
      <body>
          <div className="relative z-50">{children}</div>
      </body>
    </html>
        </ClerkProvider>
  );
}
